# WukongIM镜像
image:
  repository: registry.cn-shanghai.aliyuncs.com/wukongim/wukongim
  tag: v2.0.5-20240925

# 副本数量
replicaCount: 2

# 外部IP
externalIP: 115.29.205.135

# 管理后台域名
adminDomain: admin.test.com
# 管理后台端口
demoDomain: demo.test.com
# websocketDomain
websocketDomain: ws.test.com
# 运行模式
runMode: debug
