apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.kuboard.cn/name: wukongim
  name: wukongim
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ws
      port: 5200
      protocol: TCP
      targetPort: 5200
      nodePort: 30520

    - name: tcp
      port: 5100
      protocol: TCP
      targetPort: 5100
      nodePort: 30510

    - name: monitor
      port: 5300
      protocol: TCP
      targetPort: 5300
      nodePort: 30530

    - name: api
      port: 5001
      protocol: TCP
      targetPort: 5001
      nodePort: 30501
    - name: demo
      port: 5172
      protocol: TCP
      targetPort: 5172
      nodePort: 30172
  publishNotReadyAddresses: true
  selector:
    app: wukongim
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
